### ISSUE TITLE
done/fail/always not being called if Resolved or Rejected before function end  

### ISSUE THREAD

**Issue by josephtveter** [avoidwork/assure#8]
First off, good library. I like how fast it is compared to jquery

Here is the bug.
var Assure = require("assure");

var data = {someData: "MyData"};
var myFunction = function()
{
     var deferred = Assure();
     var hasData = true;
     if( hasData )
     {
          deferred.resolve(data);
     }
     else
     {
          // Get Data From Server
          ajax().done(deferred.resolve).fail(deferred.reject); 
     }
     return deferred;
}

var promise = myFunction();
promise.done(function(result)
{
     // If you have the data, this is never called because you never add it to the onDone array if it is resolved or rejected.
});

done fail and always should be able to be add functions to their arrays after resolve has been called.  

The Fix:

/**
 * Registers a function to execute after Promise is reconciled
 *
 * @method always
 * @param  {Function} arg Function to execute
 * @return {Object}       Deferred instance
 */
Deferred.prototype.always = function ( arg ) {
	// if ( !this.isResolved() && !this.isRejected() && typeof arg == "function" ) {
	if ( typeof arg == "function" ) {
		this.onAlways.push( arg );
	}

	return this;
};

/**
 * Registers a function to execute after Promise is resolved
 *
 * @method done
 * @param  {Function} arg Function to execute
 * @return {Object}       Deferred instance
 */
Deferred.prototype.done = function ( arg ) {
	// if ( !this.isResolved() && !this.isRejected() && typeof arg == "function" ) {
	if ( typeof arg == "function" ) {
		this.onDone.push( arg );
	}

	return this;
};

/**
 * Registers a function to execute after Promise is rejected
 *
 * @method fail
 * @param  {Function} arg Function to execute
 * @return {Object}       Deferred instance
 */
Deferred.prototype.fail = function ( arg ) {
	// if ( !this.isResolved() && !this.isRejected() && typeof arg == "function" ) {
	if ( typeof arg == "function" ) {
		this.onFail.push( arg );
	}

	return this;
};

**Comment by avoidwork** [comment]
pull request?

**Comment by avoidwork** [comment]
Hi,

Unfortunately your request goes against the spec, and can't be implemented without failing more tests.

**Comment by josephtveter** [comment]
Sorry I have not replied. I have been moving house all weekend, and thus
without internet. I have heard JQuerys promises do act differently. So It's
a feature not a bug.

**Comment by avoidwork** [comment]
The problem is your ask goes against the spec it's trying to implement, which was still moving when I created this lib, that's why some of the tests fail.
